### ISSUE TITLE
Slow build performance on some courses

### ISSUE THREAD

**Issue by PasiSa** [apluslms/gitmanager#7]
Building and deploying course content has been very slow on some courses. For example on O1 it may take 15 minutes. This meta issue collects together the recent related discussion on Teams (see [this thread](https://teams.microsoft.com/l/message/19:4dc88ac10f674b6596dc50de0979a6e1@thread.skype/1644306616945?tenantId=ae1a7724-4041-4462-a6dc-538cb199707e&groupId=b78ab778-8838-4180-940d-b9183ddc3a7c&parentMessageId=1644306616945&teamName=A%2B%20support%20for%20teachers%20and%20TAs&channelName=Development%20ideas&createdTime=1644306616945)), and some ideas for improvements.

Some log dumps from @murhum1:

    [2022-02-08 09:01:54,486] INFO:huey:12:Executing builder.builder.push_event: 345adc10-230f-44d5-b1ac-e3e72dd320b5
    [2022-02-08 09:01:54,486: INFO/api] Executing builder.builder.push_event: 345adc10-230f-44d5-b1ac-e3e72dd320b5
    [2022-02-08 09:01:54,496: DEBUG/builder] push_event: O1_2022
    ...
    <course building>
    ...
    [2022-02-08 09:05:40,409: DEBUG/configure] Compressing for https://grader.minus.cs.aalto.fi/configure
    [2022-02-08 09:06:05,096: DEBUG/configure] Configuring https://grader.minus.cs.aalto.fi/configure
    [2022-02-08 09:07:33,205: DEBUG/configure] Loading from https://grader.minus.cs.aalto.fi/configure
    [2022-02-08 09:15:35,815] INFO:huey:12:builder.builder.push_event: 345adc10-230f-44d5-b1ac-e3e72dd320b5 executed in 821.324s
    [2022-02-08 09:15:35,815: INFO/api] builder.builder.push_event: 345adc10-230f-44d5-b1ac-e3e72dd320b5 executed in 821.324s

Other dump:

    gitmanager
    ----------
    [2022-02-08 10:20:59,936: INFO/log] SECURITY INITIATE-BUILD /gitmanager/O1_2022/hook 10.42.128.2 murhum1 O1_2022 iss=gitmanager, sub=murhum1, aud=gitmanager, exp=None, permissions=[], tokens=None, verbosity=1, settings=None, pythonpath=None, traceback=False, no_color=False, force_color=False
    
    huey
    ----
    [2022-02-08 10:21:39,344: DEBUG/configure] Compressing for https://grader.minus.cs.aalto.fi/configure
    [2022-02-08 10:21:49,501: DEBUG/configure] Configuring https://grader.minus.cs.aalto.fi/configure
    
    grader
    ------
    [2022-02-08 10:22:22,351: INFO/log] SECURITY CONFIGURE ACCEPTED /configure 130.233.50.203 <access.auth.User object at 0x7ff184f7d280> course_id=218 iss=aplus, sub=gitmanager, aud=grader, exp=None, permissions=[["instance", 2, {"id": 218}]], tokens=None
    [2022-02-08 10:23:10,775: DEBUG/config] Loading course "218"
    [2022-02-08 10:23:10,783: DEBUG/config] Loading exercise "218/w01_ch01_1"
    [2022-02-08 10:23:10,786: DEBUG/config] Processed 32 tags.
    ...
    [pid: 14|app: 0|req: 1575/3471] 130.233.50.203 () {58 vars in 1488 bytes} [Tue Feb  8 10:22:20 2022] POST /configure => generated 3883732 bytes in 51640 msecs (HTTP/1.1 200) 4 headers in 662 bytes (9621 switches on core 0)
    
    huey
    ----
    [2022-02-08 10:23:12,500: DEBUG/configure] Loading from https://grader.minus.cs.aalto.fi/configure
    
    gitmanager
    ----------
    [2022-02-08 10:27:46,524: INFO/log] SECURITY APLUS-JSON /O1_2022/aplus-json 10.42.128.2 aplus O1_2022 iss=aplus, sub=aplus, aud=gitmanager, exp=None, permissions=[["instance", 1, {"id": 218}], ["instance", 2, {"id": 218}]], tokens=None
    [2022-02-08 10:27:48,401: DEBUG/course] Loading exercise "/gitmanager/courses/store/O1_2022/w01_ch01_1"
    [2022-02-08 10:27:48,433: DEBUG/parser] Processed 20 tags.
    ...
    [2022-02-08 10:28:06,832: DEBUG/course] Loading exercise "/gitmanager/courses/store/O1_2022/ennakkotietomooc"
    [2022-02-08 10:28:06,976: DEBUG/parser] Processed 160 tags.
    [pid: 13|app: 0|req: 80/312] 10.42.128.2 () {52 vars in 1314 bytes} [Tue Feb  8 10:27:46 2022] GET /O1_2022/aplus-json => generated 3916149 bytes in 21153 msecs (HTTP/1.1 200) 4 headers in 673 bytes (22 switches on core 1)
    [2022-02-08 10:28:19,666: INFO/log] SECURITY PUBLISH /O1_2022/publish 10.33.0.2 aplus O1_2022 iss=aplus, sub=aplus, aud=gitmanager, exp=None, permissions=[["instance", 1, {"id": 218}], ["instance", 2, {"id": 218}]], tokens=None
    [2022-02-08 10:28:21,525: DEBUG/course] Loading exercise "/gitmanager/courses/store/O1_2022/w01_ch01_1"
    [2022-02-08 10:28:21,554: DEBUG/parser] Processed 20 tags.
    ...
    [2022-02-08 10:28:38,705: DEBUG/course] Loading exercise "/gitmanager/courses/store/O1_2022/ennakkotietomooc"
    [2022-02-08 10:28:38,847: DEBUG/parser] Processed 160 tags.
    [2022-02-08 10:29:54,234: DEBUG/configure] Configuring https://grader.minus.cs.aalto.fi/configure
    [2022-02-08 10:29:54,243: DEBUG/connectionpool] Starting new HTTPS connection (1): minus.cs.aalto.fi:443
    [2022-02-08 10:29:59,362: DEBUG/connectionpool] https://minus.cs.aalto.fi:443 "GET /api/v2/get-token/ HTTP/1.1" 200 526
    [2022-02-08 10:29:59,373: DEBUG/connectionpool] Starting new HTTPS connection (1): grader.minus.cs.aalto.fi:443
    
    grader
    ------
    [2022-02-08 10:29:59,434: INFO/log] SECURITY PUBLISH ACCEPTED /configure 130.233.50.203 <access.auth.User object at 0x7ff184f47940> course_id=218 iss=aplus, sub=gitmanager, aud=grader, exp=None, permissions=[["instance", 2, {"id": 218}]], tokens=None
    
    gitmanager
    ----------
    [2022-02-08 10:30:33,815: DEBUG/connectionpool] https://grader.minus.cs.aalto.fi:443 "POST /configure HTTP/1.1" 200 0
    [2022-02-08 10:30:33,828: DEBUG/config] Loading course "O1_2022"
    [2022-02-08 10:30:35,656: DEBUG/course] Loading exercise "/gitmanager/courses/publish/O1_2022/w01_ch01_1"
    [2022-02-08 10:30:35,684: DEBUG/parser] Processed 20 tags.
    ...
    [2022-02-08 10:30:55,113: DEBUG/course] Loading exercise "/gitmanager/courses/publish/O1_2022/ennakkotietomooc"
    [2022-02-08 10:30:55,249: DEBUG/parser] Processed 160 tags.
    [pid: 14|app: 0|req: 60/313] 10.33.0.2 () {52 vars in 1306 bytes} [Tue Feb  8 10:28:19 2022] GET /O1_2022/publish => generated 31 bytes in 155616 msecs (HTTP/1.1 200) 4 headers in 668 bytes (1 switches on core 0)
    
    huey
    ----
    [2022-02-08 10:30:55,353] INFO:huey:12:builder.builder.push_event: 9e46755b-5a00-4a21-a975-4a551691ac9c executed in 595.387s
    [2022-02-08 10:30:55,353: INFO/api] builder.builder.push_event: 9e46755b-5a00-4a21-a975-4a551691ac9c executed in 595.387s

We should investigate where and how the performance could be improved, and collect some ideas for improvements;

- [ ] Use an application wide cache for configs (#1)
- [ ] Transfer configs between caches instead of loading separately from each directory (#2)
- [ ] Only copy the configs and static files from build directory (#5)

**Comment by lainets** [comment]
Here are a couple benchmarks of the O1 course from the latest version after the config caching was added.
```
(51.480601385235786, 'git update'), (171.140311954543, 'build'), (23.95284396596253, 'containment check'), (8.010462461039424, 'load from build'), (0.010387705639004707, 'validation warning str'), (58.09278506785631, 'configure graders'), (0.0051127839833498, 'rm'), (103.42380734533072, 'copy static dir'), (0.005849936977028847, 'find files'), (13.897881554439664, 'copy files'), (90.4047346804291, 'automatic update')

(59.11083531193435, 'git update'), (200.48943220078945, 'build'), (25.127504656091332, 'containment check'), (8.394841881468892, 'load from build'), (0.010424194857478142, 'validation warning str'), (75.11355862021446, 'configure graders'), (0.006488297134637833, 'rm'), (119.86824763193727, 'copy static dir'), (0.006324991583824158, 'find files'), (19.968127824366093, 'copy files'), (93.10923559963703, 'automatic update')

(22.96330958791077, 'git update'), (210.56050301343203, 'build'), (25.5475062597543, 'containment check'), (9.62177812308073, 'load from build'), (0.009264416992664337, 'validation warning str'), (59.210672467947006, 'configure graders'), (0.014096254482865334, 'rm'), (107.44373763911426, 'copy static dir'), (0.0057503413408994675, 'find files'), (16.476666003465652, 'copy files'), (92.45984735712409, 'automatic update')
```

It seems the network filesystem is the bottleneck. For example, the 'git update' step took less than 2 seconds when the build directory was forced to be on a local drive:
```
(1.4852809477597475, 'git update'), (50.22802898846567, 'build'), (0.8055813014507294, 'containment check'), (5.835230257362127, 'load from build'), (0.008042620494961739, 'validation warning str'), (34.60626006126404, 'configure graders'), (0.0062373001128435135, 'rm'), (69.64941806904972, 'copy static dir'), (0.0063049159944057465, 'find files'), (4.035291349515319, 'copy files'), (78.3375859670341, 'automatic update')
```
The other steps also take considerably longer when using network drives.
